### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by JohnAlbin** [JohnAlbin/zen-grids#54]
Not sure if this would be useful, but maybe. See https://github.com/RobLoach/component-installer

**Comment by macmladen** [comment]
I got a little confused by title: should it be **composer**?

Otherwise probably a good idea, however there is some pain with **all** the tools needed if form of ruby, rvm, gem, node, gulp, bower... it would be great if all could be somehow reduced or at least streamlined?

(not sure that I have idea how as the whole front end world is moving toward complexity)

**Comment by JohnAlbin** [comment]
Yeah, I prefer npm now.
