### ISSUE TITLE
Cannot activate due to conflict

### ISSUE THREAD

**Issue by petulla** [JohnAlbin/zen-grids#76]
Hi 

I'm getting the following error when running `compass watch`, hoping you can help me resolve:

```
Gem::ConflictError on line ["2112"] of /Library/Ruby/Site/2.0.0/rubygems/specification.rb: Unable to activate zen-grids-1.5, because sass-3.4.18 conflicts with sass (< 3.4, >= 3.1)
```

**Comment by mtndan** [comment]
I'm seeing the same error.

**Comment by mineschan** [comment]
any have solutions?

**Comment by jdavidlopez** [comment]
That was happening to me, too. 

It was because at the time of installing zen-grids, I had two versions of sass installed.

> sudo gem uninstall sass

> Select gem to uninstall:
> 1. sass-3.3.14
> 2. sass-3.4.18
> 3. All versions

After uninstalled the 3.4.18 version, and reinstall **zen-grids** everything worked.

**Comment by banerRana** [comment]
I uninstalled and reinstalled sass & zen-grids, but still have the conflicts, also noticed that zen-grids installs 3.3.14 even when a later version like 3.4.18 is available

my environment has
$ gem list --local

*** LOCAL GEMS ***

addressable (2.3.8)
bigdecimal (1.2.6)
chunky_png (1.3.4)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
css_parser (1.3.6)
ffi (1.9.10 x64-mingw32)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
multi_json (1.11.2)
power_assert (0.2.2)
psych (2.0.8)
rainbow (2.0.0)
rake (10.4.2)
rb-fsevent (0.9.5)
rb-inotify (0.9.5)
rdoc (4.2.0)
sass (3.4.18, 3.3.14)
scss (1.0.2)
scss-lint (0.38.0)
test-unit (3.0.8)
zen-grids (1.5)

the error is 
-----------------------------------------------------------------------
Gem::ConflictError on line ["2112"] of c: Unable to activate zen-grids-1.5, because sass-3.4.18 conflicts with sass (< 3.4, >= 3.1)
  c:/Work/Ruby22-x64/lib/ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
  c:/Work/Ruby22-x64/lib/ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
  c:/Work/Ruby22-x64/lib/ruby/2.2.0/rubygems.rb:195:in `try_activate'
  c:/Work/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
  c:/Work/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/configuration/data.rb:179:in `require'
  C:/Work/14.3/workspace/web-style-guide/src/studentLoans/config.rb:2:in `get_binding'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `eval'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `parse_string'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:15:in `block in _parse'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `open'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `_parse'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:7:in `block in new_from_file'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-core-1.0.3/lib/compass/configuration/inheritance.rb:207:in `with_defaults'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:6:in `new_from_file'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:19:in `configuration_for'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:69:in `add_project_configuration'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:25:in `configure!'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:15:in `initialize'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/commands/update_project.rb:41:in `initialize'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `new'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/bin/compass:44:in `call'
  c:/Work/Ruby22-x64/lib/ruby/gems/2.2.0/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  C:/Work/Ruby22-x64/bin/compass:23:in `load'
  C:/Work/Ruby22-x64/bin/compass:23:in `<main>'

**Comment by jdavidlopez** [comment]
As said in my previous comment, you have TWO sass versions installed, as seen in your copypaste: sass (3.4.18, 3.3.14) 

Until you solve that... it won't work. 

Cheers!

**Comment by banerRana** [comment]
when I removed sass 3.4.18 , zen-grids works, but it breaks scss-lint's dependency. This is bad as a consumer, for I need to keep my linters around . zen-grids needs to find a way to play good with the version scss-lint supports.

scss-lint-0.38.0 depends on sass (~> 3.4.1)

**Comment by JohnAlbin** [comment]
Zen Grid 1.x is not compatible with Sass 3.4; it throws a bunch of warnings about global/local variables. Zen Grids 2.x is compatible with Sass 3.4.

**Comment by JohnAlbin** [comment]
You can use a Gemfile to control which versions of Gems get used when you compile. Something like this in your project:

```Ruby
source 'https://rubygems.org'

group :frontend do
  gem 'compass',        '<= 0.13'
  # Build compass sprites faster with oily_png.
  gem 'oily_png',       '~> 1.1'
  gem 'sass',           '~> 3.2.0'
  gem 'sass-globbing',  '~> 1.1'
  gem 'zen-grids',      '~> 1.5'
end
```

You'll need to install Bundler with `gem install bundler`.

Then use bundler to force compass/sass to use the correct Gem versions:

Read the Gemfile to see if you have the correct versions: `bundle check`
Install the correct versions from your Gemfile (or Gemfile.lock, if it exists): `bundle install`
Run "compass compile" (or whatever command you want) using the proper Gem versions: `bundle exec compass compile`
